name: TuoStatic
hotpatch:
    - https://tuostudy.com/cw.js
hotconfig:
    - https://tuostudy.com/config.yaml
catch_rules:
  - rule: _
    transform_rules:
      - search: \#.+
        searchin: url
        replace: ''
      - search: _
        replace: tuostudy.onmicrosoft.cn
        action: fetch
        fetch:
          engine: fetch
          redirect: manual 
          cache:
            expire: 6*60*60*1000
      - search: (^4|^5) 
        searchin: status 
        action: return
        return:
          body: The GateWay is down! This Page is provided by ClientWorker!
          status: 503
